const raw = [
['7.1','Resources needed for Material Lab activities are identified and available.','What resources are required for this test, and how do you confirm they are available before testing starts?','Resource plan, equipment availability, consumables, approved methods, staffing.','Test execution'],
['7.1.3','Lab infrastructure is maintained so testing can be performed as intended.','Show how the lab checks that facilities, utilities, fixtures, and supporting equipment remain fit for use.','Maintenance records, utility checks, facility condition records, equipment service history.','Equipment readiness / calibration status'],
['7.1.4','Conditions that can influence test work are controlled where relevant.','Which environmental or operating conditions can affect this test, and how are they monitored or controlled?','Temperature/humidity records, environmental limits, alarms, condition checks.','Environmental or test conditions where applicable'],
['7.1.5','Monitoring and measuring resources used for test results are suitable and controlled.','Pick one active test instrument. How do you know it is suitable for the measurement being made?','Equipment specification, range/resolution, method requirement, equipment register.','Equipment readiness / calibration status'],
['7.1.5','Measurement equipment status and calibration/verification information are identifiable.','For a sampled instrument, can the user immediately determine its calibration or verification status and validity?','Calibration label, certificate, due date, equipment ID, status in register.','Equipment readiness / calibration status'],
['7.1.5','Actions are defined when measurement equipment is found unsuitable or out of tolerance.','What happens if an instrument fails calibration or is found out of tolerance? How are earlier results assessed?','Quarantine/status control, impact assessment, retest/review records, escalation record.','Abnormality / nonconforming handling'],
['7.2','Personnel performing Material Lab tests are competent and appropriately authorized.','Choose one test and one operator. What evidence shows the operator is trained, competent, and authorized for it?','Training matrix, qualification record, assessment, authorization list, refresher record.','Competence / authorization'],
['7.5','Current controlled test methods and work instructions are available where work is performed.','How does the tester know the method or work instruction being used is the current approved revision?','Controlled document system, revision number, approved WI/SOP, obsolete-copy controls.','Test method / work instruction'],
['7.5','Test records are protected, readable, retrievable, and retained as defined.','Trace one completed test record from raw data to the final result. Is it complete, readable, retrievable, and protected from unintended change?','Raw data sheet, electronic record, retention rule, access control, revision/audit trail where applicable.','Raw data / result recording'],
['8.1','Testing is planned and controlled using defined criteria and required resources.','For a current sample, how were the test requirements, method, sequence, acceptance criteria, and resources determined before work began?','Test request, test plan, specification, acceptance criteria, schedule, approved method.','Sample receipt'],
['8.5.1','Testing is carried out under controlled conditions using suitable instructions and resources.','Observe one test. Are the required method steps, settings, fixtures, software, and controls being followed?','Direct observation, current WI, machine settings, fixture ID, software/version where relevant.','Test execution'],
['8.5.2','Samples and test records remain identifiable and traceable where traceability is required.','Take one physical sample and trace it backward to its request and forward to its result. Can identity be maintained end-to-end?','Sample ID, label, traveler/request, raw data ID, result/report ID, storage location.','Sample identification / traceability'],
['8.5.2','Sample status is identifiable during preparation, testing, storage, and release.','How are untested, in-process, completed, retained, rejected, or disposed samples distinguished?','Status labels, racks/locations, system status, segregation controls.','Retention / storage'],
['8.7','Nonconforming samples, tests, or outputs are identified and controlled to prevent unintended use.','Show a recent abnormal or failed test situation. How was it contained, identified, dispositioned, and communicated?','Nonconformance record, quarantine, deviation/incident record, disposition approval, notification.','Abnormality / nonconforming handling'],
['9.1','Test and quality data are monitored and evaluated as needed to support reliable decisions.','What Material Lab data or trends are reviewed, and how are unusual patterns or recurring issues detected?','Trend chart, KPI, repeat-test rate, failure trend, review minutes, escalation records.','Calculation / data integrity'],
['9.1','Results are reviewed before they are released or used for decisions.','For one completed test, who reviewed the result and what checks were performed before release?','Reviewer sign-off, electronic approval, calculation check, specification comparison.','Review / approval'],
['10.2','Material Lab nonconformities are corrected, causes are addressed where needed, and effectiveness is checked.','Select one previous lab nonconformity. What correction, root-cause work, corrective action, and effectiveness check were completed?','NC/CAPA record, 5 Why/fishbone, action evidence, effectiveness verification, closure approval.','Corrective action / recurrence prevention'],
['7.5 / 9.1','Calculations, transfers, and reported values preserve the integrity of the original test data.','Pick one result involving calculation or transcription. Reperform the key calculation or data transfer and compare it with the reported value.','Raw values, formula/template, spreadsheet protection, independent check, final report.','Calculation / data integrity'],
];
export const STARTER_CHECKLIST = raw.map((x,i)=>({position:i+1,requirement_reference:x[0],requirement_text:x[1],question:x[2],expected_evidence:x[3],process_stage:x[4],source_type:'ISO',priority:[2,4,5,6,7,8,11,12,14,16,18].includes(i+1)?'Key control':'Normal'}));
export const ISO_SCOPE_TREE = [
  {code:'4',label:'Organization context',children:[{code:'4.1',label:'Internal/external issues, including climate-change relevance'},{code:'4.2',label:'Interested parties and relevant requirements'},{code:'4.3',label:'Quality management system scope'},{code:'4.4',label:'Quality management system processes',children:[{code:'4.4.1',label:'QMS processes, criteria, resources, responsibilities and improvement'},{code:'4.4.2',label:'Documented information supporting process operation and confidence'}]}]},
  {code:'5',label:'Leadership',children:[{code:'5.1',label:'Leadership and commitment',children:[{code:'5.1.1',label:'General leadership commitment'},{code:'5.1.2',label:'Customer focus'}]},{code:'5.2',label:'Quality policy',children:[{code:'5.2.1',label:'Establishing the quality policy'},{code:'5.2.2',label:'Communicating the quality policy'}]},{code:'5.3',label:'Roles, responsibilities and authorities'}]},
  {code:'6',label:'Planning',children:[{code:'6.1',label:'Risks and opportunities',children:[{code:'6.1.1',label:'Determine risks and opportunities to address'},{code:'6.1.2',label:'Plan, integrate and evaluate actions'}]},{code:'6.2',label:'Quality objectives and plans to achieve them',children:[{code:'6.2.1',label:'Establish, monitor and maintain quality objectives'},{code:'6.2.2',label:'Plan actions to achieve quality objectives'}]},{code:'6.3',label:'Planning changes'}]},
  {code:'7',label:'Support',children:[{code:'7.1',label:'Resources',children:[{code:'7.1.1',label:'Resource planning — general'},{code:'7.1.2',label:'People'},{code:'7.1.3',label:'Infrastructure'},{code:'7.1.4',label:'Environment for process operation'},{code:'7.1.5',label:'Monitoring and measuring resources',children:[{code:'7.1.5.1',label:'Monitoring and measuring resources — general'},{code:'7.1.5.2',label:'Measurement traceability'}]},{code:'7.1.6',label:'Organizational knowledge'}]},{code:'7.2',label:'Competence'},{code:'7.3',label:'Awareness'},{code:'7.4',label:'Communication'},{code:'7.5',label:'Documented information',children:[{code:'7.5.1',label:'Documented information — general'},{code:'7.5.2',label:'Creating and updating documented information'},{code:'7.5.3',label:'Control of documented information',children:[{code:'7.5.3.1',label:'Availability, suitability and protection'},{code:'7.5.3.2',label:'Distribution, access, storage, retention and change control'}]}]}]},
  {code:'8',label:'Operation',children:[{code:'8.1',label:'Operational planning and control'},{code:'8.2',label:'Requirements for products and services',children:[{code:'8.2.1',label:'Customer communication'},{code:'8.2.2',label:'Determining requirements'},{code:'8.2.3',label:'Reviewing requirements',children:[{code:'8.2.3.1',label:'Review before commitment'},{code:'8.2.3.2',label:'Retaining review information'}]},{code:'8.2.4',label:'Changes to requirements'}]},{code:'8.3',label:'Design and development',children:[{code:'8.3.1',label:'Design and development — general'},{code:'8.3.2',label:'Design and development planning'},{code:'8.3.3',label:'Design and development inputs'},{code:'8.3.4',label:'Design and development controls'},{code:'8.3.5',label:'Design and development outputs'},{code:'8.3.6',label:'Design and development changes'}]},{code:'8.4',label:'Externally provided processes, products and services',children:[{code:'8.4.1',label:'External provision — general'},{code:'8.4.2',label:'Type and extent of external-provider control'},{code:'8.4.3',label:'Information for external providers'}]},{code:'8.5',label:'Production and service provision',children:[{code:'8.5.1',label:'Controlled production/service conditions'},{code:'8.5.2',label:'Identification and traceability'},{code:'8.5.3',label:'Customer or external-provider property'},{code:'8.5.4',label:'Preservation'},{code:'8.5.5',label:'Post-delivery activities'},{code:'8.5.6',label:'Control of changes'}]},{code:'8.6',label:'Release of products and services'},{code:'8.7',label:'Control of nonconforming outputs',children:[{code:'8.7.1',label:'Control and disposition of nonconforming outputs'},{code:'8.7.2',label:'Documented information for nonconforming outputs'}]}]},
  {code:'9',label:'Performance evaluation',children:[{code:'9.1',label:'Monitoring, measurement, analysis and evaluation',children:[{code:'9.1.1',label:'Monitoring and measurement — general'},{code:'9.1.2',label:'Customer satisfaction'},{code:'9.1.3',label:'Analysis and evaluation'}]},{code:'9.2',label:'Internal audit',children:[{code:'9.2.1',label:'Internal audits at planned intervals'},{code:'9.2.2',label:'Audit programme, criteria, reporting and follow-up'}]},{code:'9.3',label:'Management review',children:[{code:'9.3.1',label:'Management review — general'},{code:'9.3.2',label:'Management review inputs'},{code:'9.3.3',label:'Management review outputs'}]}]},
  {code:'10',label:'Improvement',children:[{code:'10.1',label:'Improvement — general'},{code:'10.2',label:'Nonconformity and corrective action',children:[{code:'10.2.1',label:'Correction, cause, action and effectiveness'},{code:'10.2.2',label:'Documented evidence of nonconformity and action'}]},{code:'10.3',label:'Continual improvement'}]}
];
export function flattenScopeTree(nodes=ISO_SCOPE_TREE,parentCode=''){const out=[];for(const node of nodes){out.push({...node,parentCode,children:node.children||[]});if(node.children?.length)out.push(...flattenScopeTree(node.children,node.code));}return out;}
const SCOPE_FLAT=flattenScopeTree();
const SCOPE_MAP=new Map(SCOPE_FLAT.map(x=>[x.code,x]));
const SCOPE_ORDER=new Map(SCOPE_FLAT.map((x,i)=>[x.code,i]));
export function scopeLabel(code){return SCOPE_MAP.get(String(code))?.label||String(code||'')}
export function expandScopeSelection(selected=[]){const leaves=[];const seen=new Set();const collect=node=>{if(node?.children?.length){for(const child of node.children)collect(child);return}if(node?.code&&!seen.has(node.code)){seen.add(node.code);leaves.push(node.code)}};for(const rawCode of selected){const code=String(rawCode||'').trim();if(!code)continue;const node=SCOPE_MAP.get(code);if(node)collect(node);else if(!seen.has(code)){seen.add(code);leaves.push(code)}}return leaves.sort((a,b)=>(SCOPE_ORDER.get(a)??9999)-(SCOPE_ORDER.get(b)??9999)||a.localeCompare(b,undefined,{numeric:true}));}
function splitRefs(ref=''){return String(ref).split('/').map(x=>x.trim()).filter(Boolean)}
function relatedClause(a,b){return a===b||a.startsWith(`${b}.`)||b.startsWith(`${a}.`)}
function detailedCoversLeaf(item,leaf){return splitRefs(item.requirement_reference).some(ref=>ref===leaf||(leaf.startsWith(`${ref}.`)&&ref.split('.').length>=3));}
export function buildChecklistForScopes(selected=[]){const requested=[...new Set((selected||[]).map(x=>String(x||'').trim()).filter(Boolean))];if(!requested.length)return STARTER_CHECKLIST.map((x,i)=>({...x,position:i+1}));const leaves=expandScopeSelection(requested);const detailed=STARTER_CHECKLIST.filter(item=>splitRefs(item.requirement_reference).some(ref=>leaves.some(leaf=>relatedClause(ref,leaf))));const generic=[];for(const leaf of leaves){if(detailed.some(item=>detailedCoversLeaf(item,leaf)))continue;const label=scopeLabel(leaf);generic.push({requirement_reference:leaf,requirement_text:`Selected ISO 9001 audit scope: ${label}.`,question:`For ISO 9001 clause ${leaf} — ${label}, show how this scope is addressed in the lab. What objective evidence demonstrates implementation and effectiveness?`,expected_evidence:'Applicable controlled documents, records, responsibilities, monitoring results and other objective evidence relevant to the selected scope.',process_stage:'Selected ISO scope',source_type:'ISO',priority:'Normal'});}return [...detailed,...generic].map((x,i)=>({...x,position:i+1}));}
export function inviteTokenFromUrl(value=''){const u=new URL(String(value||''),'https://audit.invalid/');const queryToken=u.searchParams.get('invite')||'';const hashParams=new URLSearchParams(u.hash.replace(/^#/,'')||'');return hashParams.get('invite')||queryToken;}
export function formatScopeSelection(selected=[]){return [...new Set((selected||[]).map(x=>String(x||'').trim()).filter(Boolean))].sort((a,b)=>(SCOPE_ORDER.get(a)??9999)-(SCOPE_ORDER.get(b)??9999)||a.localeCompare(b,undefined,{numeric:true})).map(code=>`${code} ${scopeLabel(code)}`);}
export function canCreateAudit(role){return role==='admin'||role==='lead_auditor'}
export function canInvite(role){return role==='admin'}
export function canDeleteAudit(profileRole,audit,userId){if(profileRole==='admin')return true;if(profileRole!=='lead_auditor'||!audit||!userId)return false;return audit.created_by===userId||audit.lead_auditor_id===userId;}
export function canEditAudit(profileRole,audit,userId,assignmentRole){if(profileRole==='admin')return true;if(!audit||!userId||profileRole==='viewer')return false;if(audit.created_by===userId||audit.lead_auditor_id===userId)return true;return assignmentRole==='lead'||assignmentRole==='auditor';}
export function canManageAudit(profileRole,audit,userId,assignmentRole){if(profileRole==='admin')return true;if(!audit||!userId||profileRole==='viewer')return false;if(audit.created_by===userId||audit.lead_auditor_id===userId)return true;return assignmentRole==='lead';}
const RESULTS=new Set(['unanswered','conform','observation','ofi','minor_nc','major_nc']);
export function normalizeResult(value){return RESULTS.has(value)?value:'unanswered'}
export function csvCell(value){let s=String(value??'');if(/^[=+\-@]/.test(s))s="'"+s;return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
export function inviteSignupPayload(email,password,token){return {email,password,data:{invite_token:token}}}
function slug(s){return String(s||'file').toLowerCase().normalize('NFKD').replace(/[^a-z0-9.]+/g,'-').replace(/^-+|-+$/g,'')||'file'}
export function evidencePath(auditId,kind,recordId,fileName){return `${auditId}/${kind}/${recordId}/${slug(fileName)}`}
export function completionStats(rows){const out={total:rows.length,answered:0,percent:0,conform:0,observation:0,ofi:0,minor_nc:0,major_nc:0};for(const r of rows){const v=normalizeResult(r?.result);if(v!=='unanswered'){out.answered++;out[v]++;}}out.percent=out.total?Math.round(out.answered/out.total*100):0;return out;}