import { buildChecklistForScopes, formatScopeSelection, evidencePath, canEditAudit, canManageAudit } from './core.mjs';
const enc=v=>encodeURIComponent(v);
const first=x=>Array.isArray(x)?x[0]:x;
export class AuditService{
  constructor(api){this.api=api}
  uid(){const id=this.api.user?.id;if(!id)throw new Error('Not signed in');return id}
  async profile(){return first(await this.api.request(`/rest/v1/profiles?id=eq.${enc(this.uid())}&select=*`))}
  async labs(){return await this.api.request('/rest/v1/labs?select=id,name,department_id&order=name.asc')||[]}
  async audits(){const rows=await this.api.request('/rest/v1/audits?select=*&order=audit_date.desc,created_at.desc')||[];const labs=await this.labs(),map=new Map(labs.map(x=>[x.id,x.name]));return rows.map(x=>({...x,lab_name:map.get(x.lab_id)||'Lab'}));}
  async dashboard(){const [profile,labs,audits]=await Promise.all([this.profile(),this.labs(),this.audits()]);return {profile,labs,audits}}
  async createAudit(input){const uid=this.uid();const scopeClauses=[...new Set((input.scope_clauses||[]).map(x=>String(x||'').trim()).filter(Boolean))];const formattedScope=formatScopeSelection(scopeClauses);const criteria=input.criteria||`ISO 9001:2015 + Amd 1:2024${formattedScope.length?` — ${formattedScope.join('; ')}`:''} + applicable SOP/WI`;const payload={title:input.title,lab_id:input.lab_id,audit_date:input.audit_date,scope:input.scope||'',scope_clauses:scopeClauses,auditee:input.auditee||'',objective:input.objective||'',criteria,status:'draft',lead_auditor_id:uid,created_by:uid};const audit=first(await this.api.request('/rest/v1/audits',{method:'POST',body:payload,prefer:'return=representation'}));if(!audit?.id)throw new Error('Audit creation returned no ID');await this.api.request('/rest/v1/audit_members',{method:'POST',body:{audit_id:audit.id,user_id:uid,assignment_role:'lead'},prefer:'resolution=merge-duplicates'});const checklist=buildChecklistForScopes(scopeClauses);if(checklist.length)await this.api.request('/rest/v1/checklist_items',{method:'POST',body:checklist.map(x=>({...x,audit_id:audit.id})),prefer:'return=minimal'});return audit;}
  async loadAudit(id){const audit=first(await this.api.request(`/rest/v1/audits?id=eq.${enc(id)}&select=*`));if(!audit)throw new Error('Audit not found or you do not have access');const [items,responses,findings,evidence]=await Promise.all([this.api.request(`/rest/v1/checklist_items?audit_id=eq.${enc(id)}&select=*&order=position.asc`),this.api.request('/rest/v1/audit_responses?select=*'),this.api.request(`/rest/v1/findings?audit_id=eq.${enc(id)}&select=*&order=created_at.asc`),this.api.request(`/rest/v1/evidence_files?audit_id=eq.${enc(id)}&select=*&order=created_at.asc`)]);const itemIds=new Set((items||[]).map(x=>x.id));const filteredResponses=(responses||[]).filter(x=>itemIds.has(x.checklist_item_id));const findingIds=(findings||[]).map(x=>x.id);let actions=[];if(findingIds.length)actions=await this.api.request(`/rest/v1/corrective_actions?finding_id=in.(${findingIds.map(enc).join(',')})&select=*`)||[];const profile=await this.profile();const membership=first(await this.api.request(`/rest/v1/audit_members?audit_id=eq.${enc(id)}&user_id=eq.${enc(this.uid())}&select=assignment_role`));const assignmentRole=membership?.assignment_role||null;const canEdit=canEditAudit(profile?.role,audit,this.uid(),assignmentRole);const canManage=canManageAudit(profile?.role,audit,this.uid(),assignmentRole);let teamProfiles=[];if(canManage)teamProfiles=await this.teamProfiles();return {audit,profile,assignmentRole,items:items||[],responses:new Map(filteredResponses.map(x=>[x.checklist_item_id,x])),findings:findings||[],actions,evidence:evidence||[],canEdit,canManage,teamProfiles};}
  async saveResponse(checklistItemId,data){const payload={checklist_item_id:checklistItemId,result:data.result||'unanswered',evidence_text:data.evidence_text||'',notes:data.notes||'',sample_references:data.sample_references||'',follow_up:Boolean(data.follow_up),answered_by:this.uid()};return first(await this.api.request('/rest/v1/audit_responses?on_conflict=checklist_item_id',{method:'POST',body:payload,prefer:'resolution=merge-duplicates,return=representation'}));}
  async createFinding(data){const payload={audit_id:data.audit_id,response_id:data.response_id||null,checklist_item_id:data.checklist_item_id||null,classification:data.classification,requirement_reference:data.requirement_reference||'',requirement_text:data.requirement_text||'',evidence:data.evidence||'',statement:data.statement||'',risk_impact:data.risk_impact||'',immediate_correction:data.immediate_correction||'',verification_method:data.verification_method||'',verification_status:'',status:'open',owner_name:data.owner_name||'',due_date:data.due_date||null,created_by:this.uid()};return first(await this.api.request('/rest/v1/findings',{method:'POST',body:payload,prefer:'return=representation'}));}
  async saveFinding(id,data){return first(await this.api.request(`/rest/v1/findings?id=eq.${enc(id)}`,{method:'PATCH',body:data,prefer:'return=representation'}));}
  async saveCAPA(findingId,data){const existing=await this.api.request(`/rest/v1/corrective_actions?finding_id=eq.${enc(findingId)}&select=id`);if(existing?.length)return first(await this.api.request(`/rest/v1/corrective_actions?id=eq.${enc(existing[0].id)}`,{method:'PATCH',body:{root_cause:data.root_cause||'',action_text:data.action_text||'',owner_name:data.owner_name||'',due_date:data.due_date||null,verification_text:data.verification_text||''},prefer:'return=representation'}));return first(await this.api.request('/rest/v1/corrective_actions',{method:'POST',body:{finding_id:findingId,root_cause:data.root_cause||'',action_text:data.action_text||'',owner_name:data.owner_name||'',due_date:data.due_date||null,verification_text:data.verification_text||''},prefer:'return=representation'}));}
  async teamProfiles(){return await this.api.request('/rest/v1/profiles?active=eq.true&select=id,display_name,email,role&order=display_name.asc,email.asc')||[];}
  async assignMember(auditId,userId,assignmentRole='auditor'){if(!['lead','auditor','viewer'].includes(assignmentRole))throw new Error('Invalid assignment role');return first(await this.api.request('/rest/v1/audit_members?on_conflict=audit_id,user_id',{method:'POST',body:{audit_id:auditId,user_id:userId,assignment_role:assignmentRole},prefer:'resolution=merge-duplicates,return=representation'}));}
  async deleteAudit(auditId){const rows=await this.api.request(`/rest/v1/audits?id=eq.${enc(auditId)}`,{method:'DELETE',prefer:'return=representation'});const deleted=first(rows);if(!deleted)throw new Error('Audit not found or deletion is not permitted');return deleted;}
  async createInvite(role='auditor',days=7,origin=location.origin+'/'){const expires=new Date(Date.now()+Number(days)*86400000).toISOString();const invite=first(await this.api.request('/rest/v1/team_invites',{method:'POST',body:{role,expires_at:expires,created_by:this.uid()},prefer:'return=representation'}));const base=origin.endsWith('/')?origin:origin+'/';return {...invite,link:`${base}#invite=${encodeURIComponent(invite.token)}`};}
  async attachEvidence({auditId,kind,recordId,file}){if(!['response','finding'].includes(kind))throw new Error('Invalid evidence kind');const path=evidencePath(auditId,kind,recordId,file.name);const bytes=new Uint8Array(await file.arrayBuffer());await this.api.uploadEvidence(path,bytes,file.type||'application/octet-stream');const body={audit_id:auditId,response_id:kind==='response'?recordId:null,finding_id:kind==='finding'?recordId:null,storage_path:path,original_filename:file.name,mime_type:file.type||'application/octet-stream',size_bytes:file.size||bytes.byteLength,uploaded_by:this.uid()};return first(await this.api.request('/rest/v1/evidence_files',{method:'POST',body,prefer:'return=representation'}));}
  async evidenceUrl(path){return this.api.signedEvidenceUrl(path,900)}
}